# config.yml (VERSÃO CORRIGIDA)

database:
  influxdb:
    url: "http://db:8086"
    token: "my-super-secret-auth-token"
    org: "gcsbot_org"
    bucket: "btc_data"

# Configurações do backtest (parâmetros da simulação)
backtest:
  start_date: "-180d"
  initial_capital: 100
  commission_rate: 0.001

app:
  use_testnet: false
  force_offline_mode: false
  symbol: "BTCUSDT"

# Caminhos para dados e modelos
data_paths:
  macro_data_dir: "data/input/macro"
  historical_data_file: "data/input/history/BTCUSDT-1m-data.csv"
  kaggle_bootstrap_file: "data/input/bootstrap/kaggle_btc_1m.csv"
  models_dir: "data/models"

# Configurações do pipeline de dados
data_pipeline:
  start_date_ingestion: "-5y"
  # --- INÍCIO DA CORREÇÃO DOS NOMES DAS FEATURES ---
  # Alinhados com os nomes gerados em 'feature_engineering.py'
  regime_features: ["atr_14", "macd_diff_12_26_9", "rsi_14"]
  # --- FIM DA CORREÇÃO ---
  tags_for_master_table: ["target", "market_regime"]
  target:
    future_periods: 60
    profit_mult: 4.0
    stop_mult: 1.5

# Estratégia de Trading: o cérebro da tomada de decisão
trading_strategy:
  confidence_threshold: 0.60
  triple_barrier:
    profit_mult: 4.0
    stop_mult: 2.0
    time_limit_candles: 96

  models:
    specialists:
      # Especialista em ação de preço e microestrutura
      price_action:
        features:
          - "atr_14"
          - "bbp_20_2_0"
          - "volume_delta"
          - "cvd"

      # Especialista em sentimento e posicionamento de mercado
      market_dynamics:
        features:
          - "funding_rate_mean_24h"
          - "open_interest_pct_change_4h"
          - "fear_and_greed"
          - "fng_change_3d"

      # --- INÍCIO DA MODIFICAÇÃO: O NOVO ESPECIALISTA ---
      # Especialista em correlações e ambiente macro
      intermarket_analyst:
        features:
          - "btc_spx_corr_30d" # Correlação com o mercado de ações (risco on/off)
          - "btc_ndx_corr_30d" # Correlação com o setor de tecnologia
          - "btc_gold_corr_30d" # Correlação com o ouro (ativo de refúgio)
          - "btc_dxy_corr_30d" # Correlação com a força do dólar
          - "btc_vix_corr_30d" # Correlação com a volatilidade/medo
      # --- FIM DA MODIFICAÇÃO ---

  ensemble_weights:
    price_action: 0.4
    market_dynamics: 0.4
    intermarket_analyst: 0.2

# Configuração do dimensionamento de posição
position_sizing:
  method: "Dynamic"
  risk_per_trade: 0.02

# Configurações do otimizador de modelos (Optuna)
optimizer:
  n_trials: 100
  quality_threshold: 0.55 # Limiar de qualidade para salvar um modelo
  objective_metric: "Profit Factor"

position_management:
  profit_target_percent: 4.0
  max_concurrent_trades: 15
  capital_per_trade_percent: 1.5

dynamic_sizing:
  enabled: true
  performance_window_trades: 20 # A cada 20 trades, o bot reavalia a sua performance
  profit_factor_threshold: 1.6 # Se o Profit Factor for > 1.6, considera-se sucesso
  performance_upscale_factor: 1.2 # Se sucesso, multiplica o próximo risco por 1.2 (arrisca 20% a mais)
  performance_downscale_factor: 0.8 # Se falha, multiplica o próximo risco por 0.8 (arrisca 20% a menos)

# Configuração do logger
logging:
  level: "INFO"
