services:
  postgres:
    image: postgres:13
    container_name: gcsbot-postgres
    environment:
      POSTGRES_USER: gcs_user
      POSTGRES_PASSWORD: gcs_password
      POSTGRES_DB: gcs_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres_setup/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gcs_user -d gcs_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: gcsbot-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  app:
    build: .
    container_name: gcsbot-app
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      POSTGRES_HOST: gcsbot-postgres
    volumes:
      - .:/app
    ports:
      - "8765:8765"
    command: python3 run_api.py

volumes:
  postgres_data:
