# Ficheiro: docker-compose.yml (VERSÃO FINAL COM CONFIGURAÇÃO DE PERFORMANCE)

services:
  db:
    image: influxdb:2.7
    container_name: gcsbot-influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=user
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=gcsbot_org
      - DOCKER_INFLUXDB_INIT_BUCKET=btc_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
      # --- A GRANDE MELHORIA ESTÁ AQUI ---
      # Mapeia o nosso ficheiro de configuração local para dentro do container
      - ./config/influxdb.conf:/etc/influxdb2/influxdb.conf:ro
    command:
      [
        "influxd",
        "--bolt-path",
        "/var/lib/influxdb2/influxd.bolt",
        "--engine-path",
        "/var/lib/influxdb2/engine",
        "--config-file",
        "/etc/influxdb2/influxdb.conf",
      ]
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: gcsbot-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - INFLUXDB_URL=http://db:8086
      - INFLUXDB_TOKEN=my-super-secret-auth-token
      - INFLUXDB_ORG=gcsbot_org
      - INFLUXDB_BUCKET=btc_data
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}
      - BINANCE_TESTNET_API_KEY=${BINANCE_TESTNET_API_KEY}
      - BINANCE_TESTNET_API_SECRET=${BINANCE_TESTNET_API_SECRET}
    volumes:
      - .:/app
    command: tail -f /dev/null

volumes:
  influxdb_data:
