# Ficheiro: docker-compose.yml (VERSÃO FINAL COM CONFIGURAÇÃO DE PERFORMANCE)

services:
  db:
    image: influxdb:2.7
    container_name: gcsbot-influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=user
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=gcsbot_org
      - DOCKER_INFLUXDB_INIT_BUCKET=btc_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - ./config/influxdb.conf:/etc/influxdb2/influxdb.conf
    # A SEÇÃO "command" FOI COMPLETAMENTE REMOVIDA DAQUI
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: gcsbot-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - INFLUXDB_URL=http://db:8086
      - INFLUXDB_TOKEN=my-super-secret-auth-token
      - INFLUXDB_ORG=gcsbot_org
      - INFLUXDB_BUCKET=btc_data
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}
      - BINANCE_TESTNET_API_KEY=${BINANCE_TESTNET_API_KEY}
      - BINANCE_TESTNET_API_SECRET=${BINANCE_TESTNET_API_SECRET}
    volumes:
      - .:/app # Mantenha para desenvolvimento, remova para testar a imagem de produção
    command: tail -f /dev/null
    dns:
      - 8.8.8.8

volumes:
  influxdb_data:
