# docker-compose.yml (VERSÃO ALINHADA)

services:
  db:
    image: influxdb:2.7
    container_name: gcsbot-influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=user
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      # Estas variáveis agora vêm diretamente do ficheiro .env
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: gcsbot-app
    depends_on:
      db:
        condition: service_healthy
    # Passa o ficheiro .env inteiro para dentro do contentor
    # A aplicação Python irá lê-lo diretamente
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  influxdb_data:
