[default]
USE_TESTNET = false
SYMBOL = "BTC/USDT"
HISTORICAL_DATA_FILE = "data/historical_data.csv"
KAGGLE_BOOTSTRAP_FILE = "data/kaggle_bootstrap.csv"
TRADES_LOG_FILE = "logs/trades.csv"
BOT_STATE_FILE = "data/bot_state.json"
MODEL_METADATA_FILE = "data/model_metadata.json"
FORCE_OFFLINE_MODE = false
MAX_USDT_ALLOCATION = 1000.0
FEE_RATE = 0.001
SLIPPAGE_RATE = 0.0005
IOF_RATE = 0.0038
SESSION_MAX_DRAWDOWN = -0.1
WFO_TRAIN_MINUTES = 262800
MODEL_VALIDITY_MONTHS = 3
DCA_IN_BEAR_MARKET_ENABLED = true
DCA_DAILY_AMOUNT_USDT = 10.0
DCA_MIN_CAPITAL_USDT = 100.0
BACKTEST_START_DATE = "2023-01-01"
BACKTEST_END_DATE = "2023-12-31"
MODE = "trade"
TWITTER_USERNAME = "elonmusk"

[development]
DATABASE_URL = "postgresql://user:password@localhost/gcsbot"
BINANCE_API_KEY = "test"
BINANCE_API_SECRET = "test"
BINANCE_TESTNET_API_KEY = "test"
BINANCE_TESTNET_API_SECRET = "test"

[production]
DATABASE_URL = "@env/DATABASE_URL"
BINANCE_API_KEY = "@env/BINANCE_API_KEY"
BINANCE_API_SECRET = "@env/BINANCE_API_SECRET"
BINANCE_TESTNET_API_KEY = "@env/BINANCE_TESTNET_API_KEY"
BINANCE_TESTNET_API_SECRET = "@env/BINANCE_TESTNET_API_SECRET"
